#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 28 13:50:02 CST 2026
maven-metadata-central.xml.lastUpdated=1777355402378
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1777355402379
maven-metadata-snapshot-repo.xml.error=
maven-metadata-snapshot-repo.xml.lastUpdated=1777355402379
