#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Apr 29 09:26:54 CST 2026
maven-metadata-central.xml.lastUpdated=1777426014733
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1777426014736
maven-metadata-snapshot-repo.xml.error=
maven-metadata-snapshot-repo.xml.lastUpdated=1777426014735
