#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Apr 29 15:15:25 CST 2026
maven-metadata-central.xml.lastUpdated=1777446925160
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1777446925161
maven-metadata-snapshot-repo.xml.error=
maven-metadata-snapshot-repo.xml.lastUpdated=1777446925161
